# Generated by Django 5.1.2 on 2024-10-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ean', models.CharField(max_length=13)),
                ('price_of_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_of_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_warning', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField()),
                ('shopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
