# Generated by Django 5.1.2 on 2024-10-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivaCategory', '0001_initial'),
        ('product', '0002_product_ivacategoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ivaCategoryId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ivaCategory.ivacategory'),
        ),
    ]
