# Generated by Django 5.1.2 on 2024-10-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sell', models.BooleanField(default=False)),
                ('buy', models.BooleanField(default=False)),
                ('stock', models.BooleanField(default=False)),
                ('employee', models.BooleanField(default=False)),
                ('product', models.BooleanField(default=False)),
                ('shop', models.BooleanField(default=False)),
            ],
        ),
    ]
